name: test

on: [push]

jobs:
  prepare:
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - run: echo "${{ github.event.head_commit.message }}"

  test:
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - uses: actions/checkout@v1
      - name: test
        shell: bash
        run: |
          exit 78
      - name: Show versions
        run: |
          echo "node version: $(node -v)"
          echo "npm version: $(npm -v)"
          echo "yarn version: $(yarn -v)"
